# Generated by Django 5.2.8 on 2025-11-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('genre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genres.genre')),
            ],
            bases=('genres.genre',),
        ),
    ]
