# Generated by Django 5.2.8 on 2025-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('BRAZIL', 'Brasil'), ('USA', 'Estados Unidos')], max_length=100, null=True),
        ),
    ]
